name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean verify

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/javarepo:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/javarepo:latest


